export const ACTION_STARTED = 'ACTION_STARTED';
export const ACTION_ERROR = 'ACTION_ERROR';
export const ACTION_SUCCESS = 'ACTION_SUCCESS';
export const REMOVE_STATE_ERROR = 'REMOVE_STATE_ERROR';
export const REMOVE_STATE_MESSAGE = 'REMOVE_STATE_MESSAGE';

export const LOAD_USER = 'LOAD_USER';
export const USER_SIGN_UP = 'USER_SIGN_UP';
export const USER_LOGIN = 'USER_LOGIN';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';

export const CREATE_AVAILABILITY = 'CREATE_AVAILABILITY';
export const GET_AVAILABILITY = 'GET_AVAILABILITY';

export const GET_SESSIONS = 'GET_SESSIONS';
export const GET_VOLUNTEER_SESSIONS = 'GET_VOLUNTEER_SESSIONS';
export const CREATE_SESSION = 'CREATE_SESSION';
